trigger:
  - feature*
  - develop
  - drop*
  - stage
  - main

pool:
  vmImage: windows-latest

steps:

  - task: DownloadSecureFile@1
    displayName: 01 | download maven settings file
    name: settingsxml
    inputs:
      secureFile: 'settings.xml'

   
  - task: PowerShell@2
    displayName: 02 | configure maven settings
    inputs:
      targetType: 'inline'
      script: |
        New-Item -Type Directory -Force "${HOME}/.m2"
        Copy-Item -Force "$(settingsxml.secureFilePath)" "${HOME}/.m2/settings.xml"

  - task: Maven@4
    displayName: '01 || Build Maven'
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'clean package'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.17'
      mavenVersionOption: 'Default'
      mavenAuthenticateFeed: false
      effectivePomSkip: false
      sonarQubeRunAnalysis: false

  - task: CopyFiles@2
    displayName: '02 || Copy Files'
    inputs:
      SourceFolder: $(System.DefaultWorkingDirectory)
      Contents: |
        **/artifacts/**
        **/azure-functions/**
        pom.xml
        ${HOME}/.m2/settings.xml
      TargetFolder: $(Build.ArtifactStagingDirectory)
      OverWrite: true

  - task: PublishBuildArtifacts@1
    displayName: '03 || Publish Build Artifacts'
    inputs:
      PathtoPublish: $(Build.ArtifactStagingDirectory)
